In [1]:
import torch

# Everything in pytorch is based on Tensor operations.
# A tensor can have different dimensions
# so it can be 1d, 2d, or even 3d and higher

# scalar, vector, matrix, tensor

# torch.empty(size): uninitiallized
x = torch.empty(1) # scalar
print(x)


tensor([1.6484e+22])


In [2]:
x = torch.empty(3) # vector, 1D
print(x)

tensor([-7.7691e+34,  3.0855e-41, -7.6093e+34])


In [3]:
x = torch.empty(2,3) # matrix, 2D
print(x)

tensor([[1.3237e-16, 4.5778e-41, 1.3237e-16],
        [4.5778e-41, 4.4842e-44, 0.0000e+00]])


In [7]:
x = torch.empty(2,2,3) # tensor, 3 dimensions
x = torch.empty(5,2,3,4) # tensor, 4 dimensions
print(x)

tensor([[[[1.3238e-16, 4.5778e-41, 1.3238e-16, 4.5778e-41],
          [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]],


        [[[0.0000e+00, 0.0000e+00, 4.8656e-22, 4.5778e-41],
          [4.8656e-22, 4.5778e-41, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]],


        [[[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0

In [8]:
# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
print(x)


tensor([[0.9569, 0.1182, 0.2326],
        [0.0961, 0.4995, 0.5439],
        [0.7390, 0.9532, 0.5929],
        [0.2428, 0.5894, 0.1614],
        [0.7331, 0.1903, 0.5761]])


In [9]:
# torch.zeros(size), fill with 0
# torch.ones(size), fill with 1
x = torch.zeros(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [10]:
# check size
print(x.size())

# check data type
print(x.dtype)

torch.Size([5, 3])
torch.float32


In [2]:
# specify types, float32 default
x = torch.zeros(5, 3, dtype=torch.float16)
print(x)

# check type
print(x.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)
torch.float16


In [3]:
# construct from data
x = torch.tensor([5.5, 3])
print(x.size())

torch.Size([2])


In [4]:
# requires_grad argument
# This will tell pytorch that it will need to calculate the gradients for this tensor
# later in your optimization steps
# i.e. this is a variable in your model that you want to optimize
x = torch.tensor([5.5, 3], requires_grad=True)

In [8]:
# Operations
y = torch.rand(2, 2)
x = torch.rand(2, 2)

# elementwise addition
z = x + y
# torch.add(x,y)
print(x)
print(y)
print(z)

tensor([[0.4775, 0.5021],
        [0.6768, 0.4837]])
tensor([[0.9756, 0.5952],
        [0.5874, 0.1146]])
tensor([[1.4531, 1.0972],
        [1.2642, 0.5983]])


In [9]:
# in place addition, everythin with a trailing underscore is an inplace operation
# i.e. it will modify the variable
# y.add_(x)

# substraction
z = x - y
z = torch.sub(x, y)
print(x)
print(y)
print(z)

tensor([[0.4775, 0.5021],
        [0.6768, 0.4837]])
tensor([[0.9756, 0.5952],
        [0.5874, 0.1146]])
tensor([[-0.4981, -0.0931],
        [ 0.0893,  0.3692]])


In [ ]:
# multiplication
z = x * y
z = torch.mul(x,y)


# division
z = x / y
z = torch.div(x,y)


In [10]:
# Slicing
x = torch.rand(5,3)
print(x)
print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1,1]) # element at 1, 1

tensor([[0.4103, 0.4500, 0.2776],
        [0.8281, 0.8154, 0.0763],
        [0.6275, 0.6444, 0.9981],
        [0.6839, 0.9291, 0.9293],
        [0.9618, 0.4350, 0.0590]])
tensor([0.4103, 0.8281, 0.6275, 0.6839, 0.9618])
tensor([0.8281, 0.8154, 0.0763])
tensor(0.8154)


In [11]:
# Get the actual value if only 1 element in your tensor
print(x[1,1].item())

0.8154423236846924


In [12]:
# Reshape with torch.view()
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
# if -1 it pytorch will automatically determine the necessary size
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [13]:
import numpy as np
# Numpy
# Converting a Torch Tensor to a NumPy array and vice versa is very easy
a = torch.ones(5)
print(a)

# torch to numpy with .numpy()
b = a.numpy()
print(b)
print(type(b))

# Carful: If the Tensor is on the CPU (not the GPU),
# both objects will share the same memory location, so changing one
# will also change the other
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [15]:
# numpy to torch with .from_numpy(x)
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

# again be careful when modifying
a += 1
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [16]:
torch.cuda.is_available()

False

In [ ]:

# by default all tensors are created on the CPU,
# but you can also move them to the GPU (only if it's available )
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    # z = z.numpy() # not possible because numpy cannot handle GPU tenors
    # move to CPU again
    z.to("cpu")       # ``.to`` can also change dtype together!
    # z = z.numpy()